version: "3"
services:
  postgres:
    container_name: postgres_auth_dev
    image: postgres:latest
    environment:
      # To hide
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

    restart: always
    healthcheck:
      test: pg_isready -U postgres

  user-service:
    container_name: user-service_auth_dev
    image: user-service-img
    environment:
      # To hide
      RESTAPI_PORT: 3002
      DB_SERVER: postgres # PostgreSQL variables.
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    restart: always
    build:
      context: ../backend/user_service/
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck: # Check if healthcheck is working
      test: curl --fail http://user-service:3002/users/getUser || exit 1

  gateway:
    container_name: apigateway_auth_dev
    image: apigateway-img
    restart: always
    build:
      context: ../gateway/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      user-service:
        condition: service_started
  auth_service:
    container_name: auth_service_auth_dev
    image: auth-service-img
    restart: always
    build:
      context: ../backend/authentication_service/
      dockerfile: Dockerfile
    environment:
      # To hide
      RESTAPI_PORT: 3004
      USER_SERVICE: user-service:3002
      SECRET_KEY: J7kPq2xRtVzLwY9fX6eG1sA4iB3oDmC8nU5hW0lZ
    # ports:
    #   - "3004:3004"
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  question-service:
    container_name: question-service
    image: question-service-img
    environment:
      RESTAPI_PORT: 3001
      DB_SERVER: mongodb://mongo:27017
      DB_PORT: 27017 # Must be the same as the port in DB_SERVER. For logging only.
    restart: always
    build:
      context: ../backend/question_service/
      dockerfile: Dockerfile

    depends_on:
      - mongo
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://question-service:3001/questions"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
volumes:
  # Persistent data
  postgres-db:
  mongo-db:
