version: "3"
services:
  frontend:
      container_name: frontend
      image: frontend-img
      environment:
        NEXT_PUBLIC_IP_ADDRESS: http://localhost
      restart: always
      build: .
      ports:
        - "3000:3000"
