apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  frontend-NEXT_PUBLIC_IP_ADDRESS: http://localhost
  auth-RESTAPI_PORT: "3004"
  auth-USER_SERVICE: user-service:3002
  postgres-DB: postgres
  question-DB_PORT: "27017"
  question-DB_SERVER: mongodb://mongo-service:27017
  question-RESTAPI_PORT: "3001"
  user-DB_DATABASE: postgres
  user-DB_PORT: "5432"
  user-DB_SERVER: postgres
  user-RESTAPI_PORT: "3002"
  matching-PORT: "8004"
  matching-RABBITMQ: amqp://rabbitmq
  ORIGIN: gateway:3000
  collaboration-PORT: "8001"
  communication-PORT: "8002"
  history-RESTAPI_PORT: "8003"
  history-DB_SERVER: mongodb://mongo-history:27017
  history-DB_PORT: "27017"
