apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: eks-peerprep
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-container
          image: 920185736846.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 3005
          env:
            - name: NEXT_PUBLIC_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: frontend-NEXT_PUBLIC_IP_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: eks-peerprep
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
