apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  labels:
    app: question
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
        - name: question-container
          image: question-service-img
          ports:
            - containerPort: 3001
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-DB_PORT
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-DB_SERVER
            - name: RESTAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-RESTAPI_PORT
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  selector:
    app: question
  ports:
    - port: 3001
      targetPort: 3001
