apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  namespace: ekr-peerprep
  labels:
    app: question-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-container
          image: 920185736846.dkr.ecr.ap-southeast-1.amazonaws.com/question-service:latest
          ports:
            - name: restapi
              containerPort: 3001
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-DB_PORT
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-DB_SERVER
            - name: RESTAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: question-RESTAPI_PORT
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: eks-peerprep
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
