apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-deployment
  namespace: eks-peerprep
  labels:
    app: history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-container
          image: history-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: history-DB_PORT
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: history-DB_SERVER
            - name: RESTAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: history-RESTAPI_PORT
          resources:
            limits:
              cpu: "200m"
            requests:
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: eks-peerprep
  labels:
    app: history-service
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
