service: question-scraper
app: question-scraper
org: sadlyharry
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x # Version compatible with puppeteer-aws-lambdaw
  httpApi:
    cors: true
  region: ap-southeast-1
  environment:
    SERVER: http://peerprep-g091.ap-southeast-1.elasticbeanstalk.com:3001/question
  timeout: 60

functions:
  scrapeQuestion:
    package:
      exclude:
        - test/**
        - node_modules/puppeteer/.local-chromium/**
    handler: src/serverless.handler
    events: # Http invocation
      - httpApi:
          method: get
          path: /scrapeQuestion/{id}