service: question-scraper
app: question-scraper
org: sadlyharry
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x # Version compatible with puppeteer-aws-lambdaw
  httpApi:
    cors: true
  region: ap-southeast-1
  environment:
    SERVER: "13.215.150.132"

functions:
  scrapeQuestion:
    handler: serverless.handler
    timeout: 20 
    events: # Http invocatiom
      - httpApi:
          method: get
          path: /scrapeQuestion/{id}