version: "3"
services:
  question-service:
    container_name: question-service
    image: question-service-img
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo: # Not needed now, since we are using the cloud-hosted Mongo Atlas
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db