version: '3'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbitmq:3.12.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

