version: "3"
services:
    communication-service:
        container_name: communication-service
        image: communication-service-img
        restart: always
        build: .
        ports:
            - "${PORT}:${PORT}"
        environment:
            PORT: ${PORT}
