apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: wkdouze/auth-service-img
          ports:
            - containerPort: 3004
          env:
            - name: RESTAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: auth-RESTAPI_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: auth-SECRET_KEY
            - name: USER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: auth-USER_SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 3004
      targetPort: 3004
