apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: eks-peerprep
  labels:
    app: config
data:
  frontend-NEXT_PUBLIC_IP_ADDRESS: http://localhost
  auth-RESTAPI_PORT: "3004"
  auth-USER_SERVICE: user-service:3002
  postgres-DB: postgres
  question-DB_PORT: "27017"
  question-DB_SERVER: mongodb://mongo-service:27017
  question-RESTAPI_PORT: "3001"
  user-DB_DATABASE: postgres
  user-DB_PORT: "5432"
  user-DB_SERVER: postgres
  user-RESTAPI_PORT: "3002"
