apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: wkdouze/frontend-img
          ports:
            - containerPort: 3005
          env:
            - name: NEXT_PUBLIC_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: frontend-NEXT_PUBLIC_IP_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
