apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: wkdouze/question-service-img
        ports:
        - containerPort: 3001
        env:
        - name: DB_PORT
          value: "27017"
        - name: DB_SERVER
          value: mongodb://mongo-service:27017
        - name: RESTAPI_PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  selector:
    app: question-service
  ports:
    - port: 3001
      targetPort: 3001

