apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: user-service-img
          ports:
            - containerPort: 3002
          env:
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: user-DB_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgres-PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: user-DB_PORT
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: user-DB_SERVER
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgres-USER
            - name: RESTAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: user-RESTAPI_PORT
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - port: 3002
      targetPort: 3002
