name: Push Images to ECR and Deploy to EB.
on: 
  push:
    branches:
      - main
env:
  AWS_REGION : ap-southeast-1
  ROLE_TO_ASSUME: arn:aws:iam::920185736846:role/GitHubAction-AssumeRoleWithAction # Get from Choon Yong  
parameters:
- name: image_parameters
  type: object
  default:
  - { Name: user-service, Path: './backend/user_service' }
  - { Name: question-service, Path: './backend/question_service' }
  - { Name: frontend, Path: './frontend' }
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:

    # Initialisation
    - name: Check out code
      uses: actions/checkout@v4

    # AWS Authentication
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
        output-credentials: true
        
    # Sanity Check
    - name: Sts GetCallerIdentity (Sanity Check)
      run: |
        aws sts get-caller-identity

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Building images
    - ${{ each image in parameters.image_parameters }}:
      - name : Build, tag, and push image to Amazon ECR ( ${{ image.Name }} )
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ image.Name }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ image.Path }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Deployment
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
        application_name: PeerPrep
        environment_name: PeerPrep-env
        version_label: 15-1 #To manually iterate
        region: ap-southeast-1
        #deployment_package: ./aws_deploy/docker-compose.yml # No change to yaml file for now
        wait_for_deployment: false  # Set to false to save Github Actions free hours
